version: "3.7"

services:
    # image project
    app:
        container_name: cubic-app
        build:
            context: .
            dockerfile: Dockerfile
        image: cubic/cubic
        restart: unless-stopped
        working_dir: /cubic
        volumes:
            - ./:/cubic
        depends_on: 
            - redis
        networks: 
            - laravel-9
    
    # nginx
    nginx:
        container_name: cubic-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8000:80"
        volumes: 
            - ./:/cubic
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9

    # db mysql
    mysql:
        container_name: cubic-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3306:3306"
        networks: 
            - laravel-9

    # queue
    queue:
        container_name: cubic-queue
        image: cubic/cubic
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/cubic
        depends_on: 
            - redis
            - app
        networks: 
            - laravel-9

    # redis
    redis:
        container_name: cubic-redis
        image: redis:latest
        networks: 
            - laravel-9

networks: 
    laravel-9:
        driver: bridge